
version: '3.1'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - flask
        volumes:
           - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - scentroom_net
        ports:
            - 80:80
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:latest
        container_name: flask
        volumes:
            - ./:/opt/code
            - /media/usb:/media/usb
        environment:
            - FLASK_APP=/opt/code/FlaskFileUploader.py
            - PORT=5000
        command: python3 -u /opt/code/FlaskFileUploader.py
        networks:
            scentroom_net:
                aliases:
                    - lushroompi-ip
        ports:
            - 8080:5000

networks:
    scentroom_net:
        
