version: '3'

services:
  rclone:
    container_name: rclone
    privileged: true
    image: "lushdigital/lushroom-rclone:staging"
    volumes:
       - /media/usb:/media/usb
    restart: always
  display:
    container_name: display
    privileged: true
    network_mode: host
    image: "lushdigital/lushroom-display:staging"
    volumes:
       - /media/usb:/media/usb
       - /dev/fb0:/dev/fb0
       - /dev/input/event0:/dev/input/event0
    environment:
       - HOSTNAME=$HOSTNAME
       - SENTRY_URL=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137
    restart: always
  player:
    container_name: player
    image: "lushdigital/lushroom-player:staging"
    privileged: true
    ports:
       - 80:80
    volumes:
       - /media/usb:/media/usb
       - /dev/vchiq:/dev/vchiq
       - /opt/vc:/opt/vc
    restart: always
    links:
      - brickd
    environment:
      - BRICKD_HOST=brickd
      - SENTRY_URL=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137
  brickd:
    container_name: brickd
    image: "lushdigital/lushroom-brickd:staging"
    privileged: true
    ports:
       - 4223:4223
    restart: always