version: "3"

services:
  rclone:
    container_name: lushroom-rclone
    privileged: true
    image: "lushdigital/lushroom-rclone:staging"
    volumes:
       - /media/usb:/media/usb
    restart: always
    environment:
      - sentry_url=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137
  display:
    container_name: lushroom-display
    privileged: true
    network_mode: host
    image: "lushdigital/lushroom-display:staging"
    volumes:
       - /media/usb:/media/usb
       - /dev/fb0:/dev/fb0
       - /dev/input/event0:/dev/input/event0
    environment:
       - HOSTNAME
       - sentry_url=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137
    restart: always
  player:
    container_name: lushroom-player
    image: "lushdigital/lushroom-player:staging"
    privileged: true
    ports:
       - 80:80
    volumes:
       - /media/usb:/media/usb
       - /dev/vchiq:/dev/vchiq
       - /opt/vc:/opt/vc
    restart: always
    environment:
      - sentry_url=https://47ba8b60e8994fd1a5979cad36185cad@sentry.io/1391137


