version: '3'

# Note: needs directory structure from:
# https://github.com/InBrewJ/auto_ssl_nginx

# For basic auth config, see
# https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

services:
  nginx-test:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./nginx-data/nginx:/etc/nginx/conf.d
      - ./nginx-data/certbot/conf:/etc/letsencrypt
      - ./nginx-data/certbot/www:/var/www/certbot
    # network_mode: host
    ports:
      - "81:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./nginx-data/certbot/conf:/etc/letsencrypt
      - ./nginx-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"